name: Services
options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
packages:
  Apollo:
    url: https://github.com/apollographql/apollo-ios
    from: 0.49.1

targets:
# Services (Framework)
  Services:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
    dependencies:
      - package: Apollo
        product: ApolloWebSocket
    settings:
      base:
        INFOPLIST_FILE:  Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ca.byziad.nouns.services
    preBuildScripts:
      - script: |
                # Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
                DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"

                while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
                  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
                    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
                    exit 1
                  fi

                  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
                done

                # Grab a reference to the directory where scripts are checked out
                SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"

                if [ -z "${SCRIPT_PATH}" ]; then
                    echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
                    exit 1
                fi

                cd "${SRCROOT}/Sources/GraphQL/Internal"

                "${SCRIPT_PATH}"/run-bundled-codegen.sh schema:download --endpoint="https://api.thegraph.com/subgraphs/name/nounsdao/nouns-subgraph"
        name: Apollo Schema Generation
      - script: |
                # Go to the build root and search up the chain to find the Derived Data Path where the source packages are checked out.
                DERIVED_DATA_CANDIDATE="${BUILD_ROOT}"

                while ! [ -d "${DERIVED_DATA_CANDIDATE}/SourcePackages" ]; do
                  if [ "${DERIVED_DATA_CANDIDATE}" = / ]; then
                    echo >&2 "error: Unable to locate SourcePackages directory from BUILD_ROOT: '${BUILD_ROOT}'"
                    exit 1
                  fi

                  DERIVED_DATA_CANDIDATE="$(dirname "${DERIVED_DATA_CANDIDATE}")"
                done

                # Grab a reference to the directory where scripts are checked out
                SCRIPT_PATH="${DERIVED_DATA_CANDIDATE}/SourcePackages/checkouts/apollo-ios/scripts"

                if [ -z "${SCRIPT_PATH}" ]; then
                    echo >&2 "error: Couldn't find the CLI script in your checked out SPM packages; make sure to add the framework to your project."
                    exit 1
                fi

                cd "${SRCROOT}/Sources"
                "${SCRIPT_PATH}"/run-bundled-codegen.sh codegen:generate --target=swift --includes=./**/*.graphql --localSchemaFile="./GraphQL/internal/schema.json" GraphQL/internal/API.swift
        name: Apollo API Codegen
        inputFiles:
          - $SRCROOT/Sources/GraphQL/Internal/schema.json
        outputFiles:
          - $SRCROOT/Sources/GraphQL/Internal/API.swift


# ServicesTests (Framework)
  ServicesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ServicesTests
    info:
      path: ServicesTests/Info.plist
    settings:
      base:
        INFOPLIST_FILE:  ServicesTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ca.byziad.nouns.services.tests
    dependencies:
      - target: Services

