name: Services
options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
  groupOrdering: 
    - order: [Sources, ServicesTests]
packages:
  SnapshotTesting:
    url: https://github.com/pointfreeco/swift-snapshot-testing.git
    from: 1.9.0

targets:
# Services (Framework)
  Services:
    type: framework
    platform: iOS
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
    settings:
      base:
        INFOPLIST_FILE:  Sources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ca.byziad.nouns.services

# ServicesTests (Framework)
  ServicesTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ServicesTests
    info:
      path: ServicesTests/Info.plist
    settings:
      base:
        INFOPLIST_FILE:  ServicesTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: ca.byziad.nouns.services.tests
    dependencies:
      - target: Services
      - package: SnapshotTesting

