name: Nouns
options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
  bundleIdPrefix: "wtf.nouns"
  groupOrdering: 
    - order: [iOS, WatchOS]
packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library.git
    from: 5.4.0
  UIComponents:
    path: Shared/UIComponents
  Services:
    path: Shared/Services

settings:
  base:
    MARKETING_VERSION: 1
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 9XX3PA6349
    CODE_SIGN_STYLE: Manual

targets:
# Nouns iOS App
  Nouns:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iOS/Sources
    settings:
      base:
        INFOPLIST_FILE: iOS/Sources/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: wtf.nouns.ios
    dependencies:
      - package: Rswift
      - package: UIComponents
      - package: Services
    scheme:
      testTargets:
        - Nouns iOS Tests
        - Nouns iOS UITests
    preBuildScripts:
      - script: |
                /usr/bin/xcrun --sdk macosx swift run rswift generate "$SRCROOT/iOS/Sources/Resources/R.generated.swift"
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/iOS/Sources/Resources/R.generated.swift
    postBuildScripts:
      - script: |
                /usr/bin/xcrun --sdk macosx swift run swiftlint lint "$SRCROOT"
        name: SwiftLint

# Nouns iOS Unit Tests
  Nouns iOS Tests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iOS/NounsTests
    settings:
      base:
        INFOPLIST_FILE: iOS/NounsTests/Info.plist
    dependencies:
      - target: Nouns

# Nouns iOS UI Tests
  Nouns iOS UITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: iOS/NounsUITests
    settings:
      base:
        INFOPLIST_FILE: iOS/NounsUITests/Info.plist
    dependencies:
      - target: Nouns

# Nouns Watch App
  Nouns Watch:
    type: application.watchapp2
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: WatchOS/NounsWatch
    dependencies:
      - target: "Nouns WatchKit Extension"
    settings:
      base:
        INFOPLIST_FILE: WatchOS/NounsWatch/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: wtf.nouns.ios.watchkitapp
  
  # Nouns WatchKit Extension
  Nouns WatchKit Extension:
    type: watchkit2-extension
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: WatchOS/NounsWatch WatchKit Extension
    settings:
      base:
        INFOPLIST_FILE:  WatchOS/NounsWatch WatchKit Extension/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: wtf.nouns.ios.watchkitapp.watchextension
    dependencies:
      - package: Rswift
    scheme:
      testTargets:
        - Nouns Watch Tests
    preBuildScripts:
      - script: |
                /usr/bin/xcrun --sdk macosx swift run rswift generate "$SRCROOT/WatchOS/NounsWatch WatchKit Extension/Utils/R.generated.swift"
        name: R.swift
        inputFiles:
          - $TEMP_DIR/rswift-lastrun
        outputFiles:
          - $SRCROOT/WatchOS/NounsWatch WatchKit Extension/Utils/R.generated.swift
    postBuildScripts:
      - script: |
                /usr/bin/xcrun --sdk macosx swift run swiftlint lint "$SRCROOT"
        name: SwiftLint

# Nouns Watch Unit Tests
  Nouns Watch Tests:
    type: bundle.unit-test
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: WatchOS/NounsWatchTests
    settings:
      base:
        INFOPLIST_FILE:  WatchOS/NounsWatchTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: wtf.nouns.ios.watchkitapp.tests
        TEST_HOST: Nouns WatchKit Extension
    dependencies:
      - target: Nouns WatchKit Extension

# Nouns Watch UI Tests
  Nouns Watch UITests:
    type: bundle.ui-testing
    platform: watchOS
    deploymentTarget: "8.0"
    sources:
      - path: WatchOS/NounsWatchUITests
    settings:
      base:
        INFOPLIST_FILE:  WatchOS/NounsWatchUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: wtf.nouns.ios.watchkitapp.uitest
        TEST_TARGET_NAME: Nouns Watch
    dependencies:
      - target: Nouns Watch
