name: Nouns

############
# Options
############

options:
  createIntermediateGroups: true
  indentWidth: 2
  tabWidth: 2
  bundleIdPrefix: "wtf.nouns"
  groupOrdering:
    - order: [ci_scripts, iOS, NounsExtensions]

############
# Packages
############

packages:
  Rswift:
    url: https://github.com/mac-cain13/R.swift.Library.git
    from: 5.4.0
  NounsUI:
    path: shared/NounsUI
  Services:
    path: shared/Services

############
# Settings
############

settings:
  base:
    MARKETING_VERSION: 1.4.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 9XX3PA6349
    VERSIONING_SYSTEM: apple-generic

############
# Include
############

include: 
  - path: iOS/project.yml
    relativePaths: false
  - path: NounsExtensions/EverydayNounExtension/project.yml
    relativePaths: false
  - path: NounsExtensions/NounOClockNotificationExtension/project.yml
    relativePaths: false
